apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: port
    port: 2379
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 10.32.3.57 
    nodeName: etcd-k8s-master
  - ip: 10.32.3.58
    nodeName: etcd-k8s-master
  - ip: 10.32.3.59
    nodeName: etcd-k8s-master
  ports:
  - name: port
    port: 2379
    protocol: TCP
