apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-metrics
  namespace: ingress-controller 
  labels:
    k8s-app: ingress-nginx
  annotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: metrics 
    port: 9913
    protocol: TCP
  selector:
    k8s-app: ingress-nginx
