apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    k8s-app: kafka-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics 
    protocol: TCP
    port: 9308
    targetPort: 9308
  selector:
    k8s-app: kafka-exporter
